products:
  -
    name: 'Kreissaege Frameset'
    url: 'https://standert.de/collections/kreissaege/products/kreissage-rim-frameset-leadout-lemon'
    text: '52 PC™: Out of stock'
  
  -
    name: 'Kreissaege Complete Bike'
    url: 'https://standert.de/collections/kreissaege/products/kreissage-rim-leadout-lemon-complete-bike'
    text: '52 PC™: Out of stock'

  - 
    name: 'Ultegra R8170 groupset'
    url: 'https://alexscycle.com/collections/components-groupset/products/shimano-ultegra-12-speed-r8170-priority-package'
    text: 'Out of stock'